---
name: earthlyls
description: |
  A fast language server for earthly.
homepage: https://github.com/glehmann/earthly
licenses:
  - MIT
languages:
  - earthfile
categories:
  - LSP

source:
  # renovate:versioning=loose
  id: pkg:github/glehmann/earthlyls@0.1.2
  asset:
    - target: linux_x64
      file: earthlyls-{{ version }}-linux-amd64.tar.gz
      bin: earthlyls-{{ version }}-linux-amd64/earthlyls
    - target: linux_arm64
      file: earthlyls-{{ version }}-linux-arm64.tar.gz
      bin: earthlyls-{{ version }}-linux-arm64/earthlyls
    - target: darwin_x64
      file: earthlyls-{{ version }}-macos-amd64.tar.gz
      bin: earthlyls-{{ version }}-macos-amd64/earthlyls
    - target: darwin_arm64
      file: earthlyls-{{ version }}-macos-arm64.tar.gz
      bin: earthlyls-{{ version }}-macos-arm64/earthlyls
    - target: win_x64
      file: earthlyls-{{ version }}-windows-amd64.tar.gz
      bin: earthlyls-{{ version }}-windows-amd64/earthlyls.exe

bin:
  earthlyls: "{{source.asset.bin}}"
